//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TableAffected { get; set; }
        public string AuditLog { get; set; }
        public string UndoCommand { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogType { get; set; }
    }
}
