//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string Recipient { get; set; }
    }
}
