//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLogException
    {
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string AgentId { get; set; }
        public string TerminalId { get; set; }
        public string Code { get; set; }
        public string ResidentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string RevenueCode { get; set; }
        public string Amount { get; set; }
        public string PaymentReference { get; set; }
        public string TransactionDate { get; set; }
        public string UploadDate { get; set; }
        public string Status { get; set; }
        public string UploadError { get; set; }
        public string ResolutionError { get; set; }
        public Nullable<int> ResolutionStatus { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
    }
}
